spin_manifest_version = 2

[application]
authors = ["Thorsten Hans <thorsten.hans@gmail.com>"]
description = "Sample to demonstrate the usage of the HTTP router"
name = "http-router"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "http-router"

[component.http-router]
source = "target/http-router.wasm"
exclude_files = ["**/node_modules"]
[component.http-router.build]
command = "npm run build"
